// <auto-generated />
using System;
using CardsAgainstHumanity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardsAgainstHumanity.Models.Migrations
{
    [DbContext(typeof(CardsAgainstHumanityAPIContext))]
    partial class CardsAgainstHumanityAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardsAgainstHumanity.Models.Card", b =>
                {
                    b.Property<Guid>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeckID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PickAmount")
                        .HasColumnType("int");

                    b.HasKey("CardID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("DeckID");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("CardsAgainstHumanity.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "White Cards"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Black Cards"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Blank Cards"
                        });
                });

            modelBuilder.Entity("CardsAgainstHumanity.Models.Deck", b =>
                {
                    b.Property<Guid>("DeckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeckID");

                    b.ToTable("Deck");

                    b.HasData(
                        new
                        {
                            DeckID = new Guid("66c59f97-20ea-43b2-8393-40e2662f7176"),
                            DeckName = "Dutch Deck By Thijs"
                        });
                });

            modelBuilder.Entity("CardsAgainstHumanity.Models.Card", b =>
                {
                    b.HasOne("CardsAgainstHumanity.Models.Category", "Category")
                        .WithMany("Cards")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardsAgainstHumanity.Models.Deck", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckID");
                });
#pragma warning restore 612, 618
        }
    }
}
